import ProjectDetailPage from "../ProjectDetailPage";
import { assetImage } from "@/config/assets";

const hero = assetImage("projects/ART_HOUSE/cover/HERO.webp");

// Gallery images from ART_HOUSE/3_4, kept in the order they were curated in the old page,
// with the two previously unused images (33, 34) at the end.
const photoNumbers = [
  16, 18, 19, 20, 8, 21, 23, 28, 9, 10, 22, 26, 27, 15, 29, 30, 32,
  1, 17, 14, 2, 13, 11, 12, 7, 6, 31, 25, 24, 4, 5, 3, 33, 34,
];
const photos = photoNumbers.map((n) => assetImage("projects/ART_HOUSE/3_4/" + n + ".webp"));

const Orange = ({ children }) => <span style={{ color: "#C1591C" }}>{children}</span>;

export const metadata = { title: "Art House — Spaces Architects@ka" };

export default function ArtHousePage() {
  return (
    <ProjectDetailPage
      currentId="art-house"
      title="Art House"
      location="Old Delhi"
      hero={hero}
      photos={photos}
      details={{
        Project: "Art House",
        Location: "Old Delhi",
        Client: "Mr. Dinesh Ahuja",
        Status: "Completed",
        Team: "Ar. Kapil Aggarwal, Pawan Sharma",
      }}
      description={[
        <>
          SET IN THE URBAN CONTEXT OF DELHI, THE FACADE DESIGN REFLECTS A MODERN AND CLIMATE-RESPONSIVE APPROACH TAILORED TO THE CITY'S INTENSE SEASONAL VARIATIONS. IT FEATURES A THOUGHTFUL INTERPLAY OF <Orange>VERTICAL FINS, DEEP OVERHANGS & PERFORATED METAL SCREENS</Orange> THAT NOT ONLY ENHANCE THE VISUAL LANGUAGE BUT ALSO MITIGATE HEAT GAIN—CRITICAL IN DELHI'S HOT CLIMATE. MATERIALS SUCH AS EXPOSED CONCRETE, WEATHER-RESISTANT METAL CLADDING & HIGH-PERFORMANCE GLAZING ARE USED STRATEGICALLY TO BALANCE DURABILITY WITH AESTHETICS.
        </>,
        <>
          THE FACADE'S LARGE RECESSED OPENINGS MAXIMIZE NATURAL LIGHT WHILE MINIMIZING GLARE AND THERMAL LOAD, CREATING A COMFORTABLE INDOOR ENVIRONMENT. VERTICAL ELEMENTS ADD RHYTHM AND ARTICULATION, BREAKING DOWN THE SCALE OF THE STRUCTURE AND LENDING IT A REFINED, CONTEMPORARY IDENTITY. <Orange>AT NIGHT, INTEGRATED LIGHTING SOFTLY OUTLINES THE ARCHITECTURAL FEATURES, MAKING THE BUILDING STAND OUT IN THE DENSE URBAN FABRIC.</Orange> THIS FACADE EXEMPLIFIES A BLEND OF MODERN DESIGN SENSIBILITIES AND ENVIRONMENTAL RESPONSIVENESS, WELL-SUITED FOR DELHI'S EVOLVING ARCHITECTURAL LANDSCAPE.
        </>,
        <>
          THE INTERIOR DESIGN SHOWCASES A REFINED BLEND OF <Orange>CONTEMPORARY ELEGANCE & FUNCTIONAL MINIMALISM</Orange>, CHARACTERIZED BY CLEAN LINES, LAYERED LIGHTING AND A HARMONIOUS MATERIAL PALETTE. KEY FEATURES INCLUDE OPEN-PLAN LAYOUTS, MODULAR FURNITURE AND INTEGRATED STORAGE THAT ENHANCES SPATIAL FLUIDITY. VERTICAL SLATTED PANELS, FLUTED WALL TREATMENTS AND BUILT-IN JOINERY INTRODUCE RHYTHM AND TEXTURE, WHILE RECESSED AND COVE LIGHTING DEFINE ZONES AND ADD DEPTH. GLASS PARTITIONS MAINTAIN TRANSPARENCY AND OPENNESS, OFTEN PAIRED WITH SOFT FURNISHINGS TO BALANCE ACOUSTICS AND COMFORT. PREDOMINANT MATERIALS INCLUDE WOOD VENEERS, LAMINATES, POLISHED STONE, FROSTED OR CLEAR GLASS AND MATTE FINISHES, COMPLEMENTED BY BRASS OR BLACK METAL ACCENTS. <Orange>BIOPHILIC ELEMENTS LIKE INDOOR PLANTS CONTRIBUTE TO A CALMING AMBIANCE.</Orange>
        </>,
      ]}
    />
  );
}